language: rust

rust:
  - stable
  - beta
  - nightly

before_script:
  - ./install_dependent_libraries.sh
  - rustup component add clippy-preview

script:
  - cargo test
  - cargo clippy

matrix:
  allow_failures:
    - rust: beta
    - rust: nightly

env:
  global:
    - FRUGALOS_DIR=$TRAVIS_BUILD_DIR/frugalos_working_dir
    - LD_LIBRARY_PATH=$FRUGALOS_DIR/lib
    - RUSTFLAGS="-D warnings"
